name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  update_assets:
    name: Push asset update to WordPress.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install Subversion.
      run: |
        # Check if SVN is installed, if not install it.
        if ! command -v svn &> /dev/null
        then
            sudo apt-get update -y
            sudo apt-get install -y subversion
        fi

    - name: Remove unneeded files WordPress.org deploy.
      run: |
        git rm --ignore-unmatch readme.md
        git rm --ignore-unmatch composer.json
        git rm --ignore-unmatch composer.lock
        git config --global user.email "10upbot+github@10up.com"
        git config --global user.name "10upbot on GitHub"
        git commit -m "Remove unneeded files for WordPress.org deploy"

    - name: Create .wordpress-org directory if it doesn't exist.
      run: mkdir -p .wordpress-org

    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
